### ISSUE TITLE
 Bug: In light mode some things look bad

### ISSUE THREAD

**Issue by ColomboJuan** [judicaelandria/check#14]
![image](https://user-images.githubusercontent.com/42392347/86602585-3c30ca80-bf79-11ea-9a42-7f71b78fd596.png)

## Possible solution:
![image](https://user-images.githubusercontent.com/42392347/86602673-5ff41080-bf79-11ea-9088-ab2412b46af6.png)

**Comment by judicaelandria** [comment]
Yeah, would you take this issue?
take it if you want :)

**Comment by ColomboJuan** [comment]
Yes,i added the changes in pr #15
