### ISSUE TITLE
Can add task with no title

### ISSUE THREAD

**Issue by hari-bhandari** [judicaelandria/check#17]

**Comment by judicaelandria** [comment]
Hey,
I'm sorry for this error, I will fix that
thanks for this issue

**Comment by judicaelandria** [comment]
But if you want, you can take this issue :) 
do you want to take it ?

**Comment by hari-bhandari** [comment]
sure i can help you

**Comment by judicaelandria** [comment]
Good you can take it

**Comment by hari-bhandari** [comment]
const createTask = () => {
    if(form.name){
    const task = {
      id: Math.round(Math.random() * 10000),
      name: form.name,
      completed: false,
    };
    setTasks([...tasks, task]);
    setForm(initialState);
  }};
