### ISSUE TITLE
Feature: i18n implementation

### ISSUE THREAD

**Issue by ColomboJuan** [judicaelandria/check#9]
Hi! Are you looking to translate the application into other languages ​​?, I know how to do it with React-intl, if you want I can contribute to the project

**Comment by judicaelandria** [comment]
Hey @ColomboJuan 
Thank you for your interest to this project
I'd love to, but what can we translate according to you ?

**Comment by ColomboJuan** [comment]
It is true that the application does not have much text, but it could be translated so that people from different places could use it, I could translate it into Spanish

**Comment by judicaelandria** [comment]
yeah okay, just send a PR when you finish it!
thank!
if you have a some cool features to add to this app just make a issue ;)

**Comment by judicaelandria** [comment]
thanks for your contribution!
